const SEARCH_DATA = [
  // 山・コース
  { title: "高尾山", url: "regions/kanto/takao.html", tags: "東京 関東 初級 日帰り 子連れ ケーブルカー 八王子", desc: "都心から1時間。年間300万人が訪れる初心者向けの山。" },
  { title: "富士山（吉田ルート）", url: "regions/chubu/fuji.html", tags: "静岡 山梨 中部 上級 世界遺産 2026 富士宮 御殿場", desc: "日本最高峰3,776m。7〜9月が登山シーズン。" },
  { title: "上高地・涸沢カール", url: "regions/chubu/kamikochi.html", tags: "長野 中部 中級 紅葉 アルプス 松本 安曇野", desc: "日本屈指の山岳リゾート。秋の紅葉が絶景。" },
  { title: "霧ヶ峰（車山）", url: "regions/chubu/kirigamine.html", tags: "長野 中部 初級 高原 子連れ ニッコウキスゲ 諏訪", desc: "一面のニッコウキスゲが咲く高原ハイキング。" },
  { title: "大雪山（旭岳）", url: "regions/hokkaido/daisetsuzan.html", tags: "北海道 中級 紅葉 ロープウェイ 高山植物 旭川 東川", desc: "北海道最高峰2,291m。日本最早の紅葉。" },
  { title: "知床・羅臼岳", url: "regions/hokkaido/shiretoko.html", tags: "北海道 上級 世界遺産 ヒグマ 斜里 羅臼 網走", desc: "世界自然遺産・知床の最高峰。本格登山。" },
  { title: "蔵王山", url: "regions/tohoku/zao.html", tags: "山形 宮城 東北 初級 中級 御釜 樹氷 仙台 山形市", desc: "神秘的な御釜と冬の樹氷モンスターで有名。" },
  { title: "吉野山", url: "regions/kinki/yoshino.html", tags: "奈良 近畿 初級 桜 世界遺産 春 吉野 大阪 京都", desc: "3万本の桜が咲き誇る日本一の花見山。" },
  { title: "六甲山", url: "regions/kinki/rokko.html", tags: "神戸 兵庫 近畿 初級 中級 縦走 有馬温泉 大阪 阪神", desc: "神戸の山。ロックガーデンから宝塚への縦走が人気。大阪からもアクセス良好。" },
  { title: "大山（伯耆大山）", url: "regions/chugoku/daisen.html", tags: "鳥取 中国 中級 ブナ林 紅葉 米子 島根", desc: "中国地方最高峰1,729m。伯耆富士とも呼ばれる。" },
  { title: "石鎚山", url: "regions/shikoku/ishizuchi.html", tags: "愛媛 四国 中級 鎖場 西日本最高峰 松山 高知", desc: "西日本最高峰1,982m。鎖場が続くスリリングなコース。" },
  { title: "屋久島（縄文杉）", url: "regions/kyushu/yakushima.html", tags: "鹿児島 九州 中級 世界遺産 縄文杉 トロッコ 屋久島", desc: "樹齢7,200年の縄文杉を目指す世界自然遺産の森。" },
  { title: "阿蘇山", url: "regions/kyushu/aso.html", tags: "熊本 九州 中級 火山 草千里 カルデラ 阿蘇市 大分", desc: "世界最大級のカルデラ。雄大な草千里の絶景。" },
  { title: "筑波山", url: "regions/kanto/tsukuba.html", tags: "茨城 関東 初級 中級 ケーブルカー ロープウェイ 日帰り 子連れ つくば 水戸", desc: "関東平野に浮かぶ双耳峰。ケーブルカーで手軽にアクセスできる百名山。" },
  { title: "八ヶ岳（編笠山）", url: "regions/chubu/yatsugatake.html", tags: "長野 山梨 中部 中級 百名山 アルプス 山小屋 富士見 小淵沢", desc: "南八ヶ岳の入門峰・編笠山。山小屋泊で絶景の稜線歩きが楽しめる。" },
  // 新規追加ページ
  { title: "大山（神奈川）", url: "regions/kanto/oyama.html", tags: "神奈川 関東 初級 阿夫利神社 紅葉 ケーブルカー 伊勢原 丹沢", desc: "大山詣りの名山。ケーブルカーで初心者でも登れる。紅葉が絶景。" },
  { title: "丹沢山", url: "regions/kanto/tanzawasan.html", tags: "神奈川 関東 中級 百名山 塔ノ岳 大倉 富士山 ヤマビル 渋沢", desc: "神奈川最高峰・日本百名山。大倉尾根の急登が有名。" },
  { title: "御岳山", url: "regions/kanto/mitakesan.html", tags: "東京 関東 初級 武蔵御嶽神社 ケーブルカー レンゲショウマ 犬 奥多摩 青梅", desc: "武蔵御嶽神社への参拝と渓谷美。8月のレンゲショウマが名物。" },
  { title: "雲取山", url: "regions/kanto/kumotoriyama.html", tags: "東京 埼玉 山梨 関東 中級 百名山 東京都最高峰 奥多摩 山小屋", desc: "東京都最高峰2,017m。日本百名山。1泊2日の山小屋登山が人気。" },
  { title: "羊蹄山", url: "regions/hokkaido/youteizan.html", tags: "北海道 上級 百名山 蝦夷富士 お鉢巡り 倶知安 洞爺湖", desc: "蝦夷富士の別名を持つ北海道の秀峰。端正な円錐形の百名山。" },
  { title: "利尻山", url: "regions/hokkaido/rishirizan.html", tags: "北海道 上級 百名山 利尻島 利尻富士 フェリー 稚内 礼文", desc: "利尻島に聳える孤高の独立峰・利尻富士。海越しの絶景。" },
  { title: "十勝岳", url: "regions/hokkaido/tokachidake.html", tags: "北海道 中級 百名山 活火山 富良野 美瑛 上富良野 望岳台", desc: "活火山の荒涼とした景観と美瑛・富良野の丘の展望が素晴らしい。" },
  { title: "ニセコ・ワイスホルン", url: "regions/hokkaido/niseko.html", tags: "北海道 初級 ニセコ スキー ゴンドラ 羊蹄山 倶知安 リゾート", desc: "世界屈指のパウダースノーで有名なニセコの夏ハイキング。" },
  { title: "羅臼岳", url: "regions/hokkaido/rausudake.html", tags: "北海道 上級 百名山 知床 世界遺産 ヒグマ 羅臼 斜里", desc: "世界自然遺産・知床半島の最高峰。ヒグマが多い本格上級登山。" },
  { title: "八甲田山", url: "regions/tohoku/hakkodasan.html", tags: "青森 東北 中級 百名山 樹氷 酸ヶ湯温泉 ロープウェイ 田茂萢湿原", desc: "冬の樹氷モンスターと夏のニッコウキスゲで有名な東北の名山。" },
  { title: "安達太良山", url: "regions/tohoku/adatarasan.html", tags: "福島 東北 初級 百名山 智恵子抄 ゴンドラ 沼ノ平 紅葉 二本松", desc: "智恵子抄でほんとうの空と詠まれた福島の百名山。" },
  { title: "秋田駒ヶ岳", url: "regions/tohoku/akitakomadake.html", tags: "秋田 岩手 東北 初級 コマクサ 高山植物 乳頭温泉 田沢湖 花の百名山", desc: "コマクサの大群落・花の百名山。マイカー規制あり。" },
  { title: "岩手山", url: "regions/tohoku/iwateyama.html", tags: "岩手 東北 中級 百名山 南部片富士 お鉢巡り 馬返し 盛岡", desc: "岩手県最高峰・南部片富士。お鉢巡りが醍醐味の百名山。" },
  { title: "月山", url: "regions/tohoku/gassan.html", tags: "山形 東北 初級 百名山 出羽三山 夏スキー リフト 霊山 鶴岡", desc: "出羽三山の一つ・霊山。夏スキーと高山植物で有名。" },
  { title: "乗鞍岳", url: "regions/chubu/norikuradake.html", tags: "長野 岐阜 中部 初級 百名山 バス 3000m 高山植物 コマクサ 松本", desc: "バスで2,702mまで行ける3,000m超の初心者向け高山。" },
  { title: "御嶽山", url: "regions/chubu/ontakesan.html", tags: "長野 岐阜 中部 中級 百名山 霊山 噴火 ロープウェイ 木曽福島", desc: "御嶽教の霊山。2014年噴火後も登山可能（警戒レベル確認必須）。" },
  { title: "白山", url: "regions/chubu/hakusan.html", tags: "石川 岐阜 中部 中級 百名山 三名山 クロユリ 高山植物 金沢 翠ヶ池", desc: "富士山・立山と並ぶ日本三名山。高山植物の宝庫。" },
  { title: "槍ヶ岳", url: "regions/chubu/yarigadake.html", tags: "長野 岐阜 中部 上級 百名山 北アルプス 穂先 上高地 山小屋 縦走", desc: "北アルプスの憧れの名峰。天を衝く穂先が特徴的な日本のマッターホルン。" },
  { title: "剱岳", url: "regions/chubu/tsurugigatake.html", tags: "富山 中部 上級 百名山 岩と雪の殿堂 カニのヨコバイ 立山 アルペンルート 室堂", desc: "岩と雪の殿堂。カニのヨコバイ・タテバイが難所の最難関クラス。" },
  { title: "大台ヶ原", url: "regions/kinki/odaigahara.html", tags: "奈良 三重 近畿 初級 多雨 苔 原生林 大蛇嵓 紅葉 世界遺産", desc: "国内屈指の多雨地帯・神秘的な苔の原生林。大蛇嵓の絶壁が見どころ。" },
  { title: "金剛山", url: "regions/kinki/kongosan.html", tags: "大阪 奈良 近畿 初級 回数登山 霧氷 カタクリ 富田林 年間登山者数最多", desc: "年間登山者数日本最多の大阪近郊の名山。冬の霧氷が人気。" },
  { title: "比叡山", url: "regions/kinki/hieizan.html", tags: "滋賀 京都 近畿 初級 延暦寺 世界遺産 天台宗 ケーブルカー 琵琶湖 千日回峰行", desc: "天台宗総本山・延暦寺（世界遺産）を擁する霊山。ケーブルカーでアクセス。" },
  { title: "大峰山", url: "regions/kinki/omineyama.html", tags: "奈良 近畿 中級 百名山 修験道 女人禁制 大峰奥駈道 洞川温泉 西の覗き", desc: "修験道の聖地・大峰奥駈道の要衝。女人禁制が続く霊峰。" },
  { title: "吾妻山（広島）", url: "regions/chugoku/azumayama.html", tags: "広島 島根 中国 初級 水仙 リンドウ 比婆道後帝釈 360度展望 庄原", desc: "1〜2月の水仙100万本と10月のリンドウが有名な広島の名峰。" },
  { title: "三瓶山", url: "regions/chugoku/sanbesan.html", tags: "島根 中国 初級 火山 湿原 男三瓶山 西の原 大田市 自然館サヒメル", desc: "火山地形と全国最大規模の陸化湿原を持つ島根の名峰。" },
  { title: "恐羅漢山", url: "regions/chugoku/korouhanzan.html", tags: "広島 島根 中国 中級 中国地方第2位 ブナ スキー 牛小屋高原 三次", desc: "中国地方第2位の高峰。ブナ原生林の新緑・紅葉が美しい。" },
  { title: "道後山", url: "regions/chugoku/dogoyama.html", tags: "広島 鳥取 中国 初級 草原 大山展望 JR 秘境駅 比婆道後帝釈 庄原", desc: "JR道後山駅から徒歩で登れる開放的な草原の山。大山の展望台。" },
  { title: "比婆山", url: "regions/chugoku/hibayama.html", tags: "広島 中国 初級 イザナミ 古事記 ブナ カタクリ 比婆道後帝釈 庄原 霊山", desc: "古事記のイザナミを祀る聖地。カタクリの群落とブナの神域。" },
  { title: "剣山（四国）", url: "regions/shikoku/tsurugizan.html", tags: "徳島 四国 初級 百名山 リフト 次郎笈 笹原 三好 四国第2", desc: "四国第2の高峰・百名山。リフト利用で初心者でも登れる。" },
  { title: "三嶺", url: "regions/shikoku/sanrei.html", tags: "高知 徳島 四国 中級 天空の池 笹原 剣山縦走 祖谷 大歩危", desc: "四国の秘峰。天空の池と笹原の稜線。剣山との縦走が人気。" },
  { title: "寒霞渓", url: "regions/shikoku/kankakei.html", tags: "香川 四国 初級 小豆島 紅葉 ロープウェイ 日本三大渓谷美 瀬戸内海 オリーブ", desc: "日本三大渓谷美のひとつ。小豆島の秋の紅葉が絶景。" },
  { title: "筒上山", url: "regions/shikoku/tsutsugazan.html", tags: "高知 愛媛 四国 中級 アケボノツツジ 石鎚山 土小屋 笹原 久万高原", desc: "アケボノツツジの群落が圧巻の四国の名峰。4〜5月がベスト。" },
  { title: "東赤石山", url: "regions/shikoku/higashiakaishi.html", tags: "愛媛 四国 中級 超塩基性岩 蛇紋岩 希少植物 シコタンソウ 新居浜 自然観察", desc: "超塩基性岩の特殊な植生。希少高山植物の宝庫。植物愛好家に人気。" },
  { title: "九重山（くじゅう）", url: "regions/kyushu/kujusan.html", tags: "大分 九州 初級 百名山 九州最高峰 ミヤマキリシマ 牧ノ戸峠 黒川温泉 坊ガツル", desc: "九州最高峰・中岳。6月のミヤマキリシマが圧巻の花の百名山。" },
  { title: "開聞岳", url: "regions/kyushu/kaimonodake.html", tags: "鹿児島 九州 中級 百名山 薩摩富士 独立峰 指宿温泉 砂蒸し 種子島 屋久島", desc: "薩摩富士・鹿児島の独立峰。海越しの絶景と指宿温泉がセットで人気。" },
  { title: "雲仙岳", url: "regions/kyushu/unzendake.html", tags: "長崎 九州 初級 平成新山 普賢岳 噴火 雲仙温泉 地獄 ミヤマキリシマ 島原", desc: "1990年噴火で誕生した平成新山を間近に見る。雲仙温泉・地獄が観光名所。" },
  { title: "祖母山", url: "regions/kyushu/sobozan.html", tags: "大分 宮崎 熊本 九州 中級 百名山 シャクナゲ 原生林 豊後竹田 傾山縦走", desc: "日本百名山・九州中部山地の主峰。シャクナゲと静かな山歩きが魅力。" },

  // 地域インデックス
  { title: "北海道のハイキングコース", url: "regions/hokkaido/index.html", tags: "北海道 旭川 札幌 函館 釧路 網走 大自然 温泉", desc: "北海道の人気ハイキングコース一覧。大雪山・知床など。" },
  { title: "東北のハイキングコース", url: "regions/tohoku/index.html", tags: "東北 青森 岩手 宮城 秋田 山形 福島 仙台 蔵王 八甲田", desc: "東北の人気ハイキングコース一覧。蔵王・八甲田など。" },
  { title: "関東のハイキングコース", url: "regions/kanto/index.html", tags: "関東 東京 神奈川 埼玉 千葉 群馬 栃木 茨城 横浜 さいたま", desc: "関東の人気ハイキングコース一覧。高尾山・筑波山など。" },
  { title: "中部のハイキングコース", url: "regions/chubu/index.html", tags: "中部 長野 山梨 静岡 岐阜 新潟 富山 石川 福井 名古屋 松本 甲府 富士山 アルプス", desc: "中部の人気ハイキングコース一覧。富士山・上高地・八ヶ岳など。" },
  { title: "近畿のハイキングコース", url: "regions/kinki/index.html", tags: "近畿 大阪 京都 兵庫 奈良 滋賀 和歌山 三重 神戸 六甲山 吉野", desc: "近畿の人気ハイキングコース一覧。六甲山・吉野山など。大阪・京都近郊の山も。" },
  { title: "中国地方のハイキングコース", url: "regions/chugoku/index.html", tags: "中国 広島 岡山 鳥取 島根 山口 大山 宮島", desc: "中国地方の人気ハイキングコース一覧。大山・宮島など。" },
  { title: "四国のハイキングコース", url: "regions/shikoku/index.html", tags: "四国 愛媛 高知 徳島 香川 松山 石鎚山 剣山", desc: "四国の人気ハイキングコース一覧。石鎚山・剣山など。" },
  { title: "九州のハイキングコース", url: "regions/kyushu/index.html", tags: "九州 福岡 長崎 熊本 大分 宮崎 鹿児島 沖縄 阿蘇 屋久島 由布岳", desc: "九州の人気ハイキングコース一覧。阿蘇山・屋久島など。" },

  // ブログ
  { title: "初心者向け装備ガイド", url: "blog/beginner-gear.html", tags: "装備 初心者 登山靴 ザック レインウェア", desc: "最初に揃えるべき5つのアイテムと優先順位。" },
  { title: "2026年秋の紅葉ハイキング", url: "blog/autumn-2026.html", tags: "紅葉 秋 2026 おすすめ 大雪山 上高地", desc: "全国の紅葉名山と見頃時期を解説。" },
  { title: "富士山2026年シーズン情報", url: "blog/fuji-2026.html", tags: "富士山 2026 規制 混雑 シーズン", desc: "登山規制・混雑を避けるコツ。" },
  { title: "登山の食事・行動食ガイド", url: "blog/food-guide.html", tags: "食事 行動食 栄養 エネルギー 補給 山ごはん", desc: "登山中のエネルギー補給の基本とおすすめ行動食。" },
  { title: "雨の日の登山ガイド", url: "blog/rainy-day-hiking.html", tags: "雨 天候 レインウェア 判断 悪天候", desc: "雨天時の装備・撤退判断・楽しみ方を解説。" },
  { title: "初心者向け百名山5選", url: "blog/hyakunen-beginner.html", tags: "百名山 初心者 初級 チャレンジ 筑波山 霧ヶ峰", desc: "はじめての百名山チャレンジにおすすめの5座。" },
  { title: "登山の安全対策ガイド", url: "blog/safety-guide.html", tags: "安全 遭難 緊急 装備 チェックリスト", desc: "緊急時の対処法と事前準備チェックリスト。" },
  { title: "子連れハイキングガイド", url: "blog/kids-hiking.html", tags: "子連れ 子ども ファミリー 初心者 高尾山", desc: "子どもと一緒に楽しむ初めての登山。" },
  { title: "登山アプリ比較2026", url: "blog/app-guide.html", tags: "YAMAP ヤマレコ アプリ GPS 地図", desc: "YAMAPとヤマレコを徹底比較。" },

  // 装備
  { title: "登山靴の選び方", url: "gear/shoes.html", tags: "登山靴 トレッキングシューズ 選び方 おすすめ", desc: "ローカット・ミドル・ハイカットの違いを解説。" },
  { title: "ザックの選び方", url: "gear/pack.html", tags: "ザック バックパック 選び方 容量", desc: "日帰りから縦走まで用途別のおすすめザック。" },
  { title: "レインウェアの選び方", url: "gear/rain.html", tags: "レインウェア 雨具 ゴアテックス 防水", desc: "登山用レインウェアの選び方とおすすめ。" },
  { title: "トレッキングポールの選び方", url: "gear/pole.html", tags: "ポール ストック 選び方", desc: "膝への負担を軽減するポールの使い方と選び方。" },
  { title: "ウェア・レイヤリング", url: "gear/wear.html", tags: "ウェア レイヤリング 速乾 防寒", desc: "登山の重ね着（レイヤリング）の基本。" },
  { title: "安全装備ガイド", url: "gear/safety.html", tags: "安全 ヘッドライト 救急 GPS 装備", desc: "緊急時に命を守る安全装備の選び方。" },
  { title: "高山病対策ガイド", url: "gear/altitude.html", tags: "高山病 予防 対処 富士山 北アルプス 症状 高度", desc: "高山病の症状・原因・予防法・対処法を徹底解説。" },
  { title: "富士山装備チェックリスト", url: "gear/fuji-checklist.html", tags: "富士山 装備 チェックリスト 持ち物", desc: "富士登山に必要な持ち物を完全リスト化。" },

  // 難易度・季節
  { title: "初級コース一覧", url: "difficulty/beginner.html", tags: "初級 初心者 簡単 日帰り", desc: "登山経験不要の初心者向けコース。" },
  { title: "中級コース一覧", url: "difficulty/intermediate.html", tags: "中級 体力 装備", desc: "基本装備と体力がある方向けのコース。" },
  { title: "上級コース一覧", url: "difficulty/advanced.html", tags: "上級 本格 経験者", desc: "十分な経験と装備が必要な本格登山コース。" },
  { title: "春のハイキング", url: "season/spring.html", tags: "春 桜 新緑 3月 4月 5月", desc: "桜・新緑を楽しむ春のおすすめコース。" },
  { title: "夏のハイキング", url: "season/summer.html", tags: "夏 富士山 アルプス 高山 6月 7月 8月", desc: "夏山・高山植物・富士登山の季節。" },
  { title: "秋のハイキング", url: "season/autumn.html", tags: "秋 紅葉 9月 10月 11月", desc: "紅葉が最高潮の秋のおすすめコース。" },
  { title: "冬のハイキング", url: "season/winter.html", tags: "冬 雪 スノーシュー 樹氷 12月 1月 2月", desc: "雪山・スノーシューを楽しむ冬のコース。" },
];
