const SEARCH_DATA = [
  { title: "高尾山", url: "regions/kanto/takao.html", tags: "東京 関東 初級 日帰り 子連れ ケーブルカー", desc: "都心から1時間。年間300万人が訪れる初心者向けの山。" },
  { title: "富士山（吉田ルート）", url: "regions/chubu/fuji.html", tags: "静岡 山梨 中部 上級 世界遺産 2026", desc: "日本最高峰3,776m。7〜9月が登山シーズン。" },
  { title: "上高地・涸沢カール", url: "regions/chubu/kamikochi.html", tags: "長野 中部 中級 紅葉 アルプス", desc: "日本屈指の山岳リゾート。秋の紅葉が絶景。" },
  { title: "霧ヶ峰（車山）", url: "regions/chubu/kirigamine.html", tags: "長野 中部 初級 高原 子連れ ニッコウキスゲ", desc: "一面のニッコウキスゲが咲く高原ハイキング。" },
  { title: "大雪山（旭岳）", url: "regions/hokkaido/daisetsuzan.html", tags: "北海道 中級 紅葉 ロープウェイ 高山植物", desc: "北海道最高峰2,291m。日本最早の紅葉。" },
  { title: "知床・羅臼岳", url: "regions/hokkaido/shiretoko.html", tags: "北海道 上級 世界遺産 ヒグマ", desc: "世界自然遺産・知床の最高峰。本格登山。" },
  { title: "蔵王山", url: "regions/tohoku/zao.html", tags: "山形 宮城 東北 初級 中級 御釜 樹氷", desc: "神秘的な御釜と冬の樹氷モンスターで有名。" },
  { title: "吉野山", url: "regions/kinki/yoshino.html", tags: "奈良 近畿 初級 桜 世界遺産 春", desc: "3万本の桜が咲き誇る日本一の花見山。" },
  { title: "六甲山", url: "regions/kinki/rokko.html", tags: "神戸 兵庫 近畿 初級 中級 縦走 有馬温泉", desc: "神戸の山。ロックガーデンから宝塚への縦走が人気。" },
  { title: "大山（伯耆大山）", url: "regions/chugoku/daisen.html", tags: "鳥取 中国 中級 ブナ林 紅葉", desc: "中国地方最高峰1,729m。伯耆富士とも呼ばれる。" },
  { title: "石鎚山", url: "regions/shikoku/ishizuchi.html", tags: "愛媛 四国 中級 鎖場 西日本最高峰", desc: "西日本最高峰1,982m。鎖場が続くスリリングなコース。" },
  { title: "屋久島（縄文杉）", url: "regions/kyushu/yakushima.html", tags: "鹿児島 九州 中級 世界遺産 縄文杉 トロッコ", desc: "樹齢7,200年の縄文杉を目指す世界自然遺産の森。" },
  { title: "阿蘇山", url: "regions/kyushu/aso.html", tags: "熊本 九州 中級 火山 草千里 カルデラ", desc: "世界最大級のカルデラ。雄大な草千里の絶景。" },
  { title: "初心者向け装備ガイド", url: "blog/beginner-gear.html", tags: "装備 初心者 登山靴 ザック レインウェア", desc: "最初に揃えるべき5つのアイテムと優先順位。" },
  { title: "2026年秋の紅葉ハイキング", url: "blog/autumn-2026.html", tags: "紅葉 秋 2026 おすすめ 大雪山 上高地", desc: "全国の紅葉名山と見頃時期を解説。" },
  { title: "富士山2026年シーズン情報", url: "blog/fuji-2026.html", tags: "富士山 2026 規制 混雑 シーズン", desc: "登山規制・混雑を避けるコツ。" },
  { title: "筑波山", url: "regions/kanto/tsukuba.html", tags: "茨城 関東 初級 中級 ケーブルカー ロープウェイ 日帰り 子連れ", desc: "関東平野に浮かぶ双耳峰。ケーブルカーで手軽にアクセスできる百名山。" },
  { title: "八ヶ岳（編笠山）", url: "regions/chubu/yatsugatake.html", tags: "長野 山梨 中部 中級 百名山 アルプス 山小屋", desc: "南八ヶ岳の入門峰・編笠山。山小屋泊で絶景の稜線歩きが楽しめる。" },
  { title: "登山の食事・行動食ガイド", url: "blog/food-guide.html", tags: "食事 行動食 栄養 エネルギー 補給 山ごはん", desc: "登山中のエネルギー補給の基本とおすすめ行動食。" },
  { title: "雨の日の登山ガイド", url: "blog/rainy-day-hiking.html", tags: "雨 天候 レインウェア 判断 悪天候", desc: "雨天時の装備・撤退判断・楽しみ方を解説。" },
  { title: "初心者向け百名山5選", url: "blog/hyakunen-beginner.html", tags: "百名山 初心者 初級 チャレンジ 筑波山 霧ヶ峰", desc: "はじめての百名山チャレンジにおすすめの5座。" },
  { title: "登山の安全対策ガイド", url: "blog/safety-guide.html", tags: "安全 遭難 緊急 装備 チェックリスト", desc: "緊急時の対処法と事前準備チェックリスト。" },
  { title: "子連れハイキングガイド", url: "blog/kids-hiking.html", tags: "子連れ 子ども ファミリー 初心者 高尾山", desc: "子どもと一緒に楽しむ初めての登山。" },
  { title: "登山アプリ比較2026", url: "blog/app-guide.html", tags: "YAMAP ヤマレコ アプリ GPS 地図", desc: "YAMAPとヤマレコを徹底比較。" },
  { title: "登山靴の選び方", url: "gear/shoes.html", tags: "登山靴 トレッキングシューズ 選び方 おすすめ", desc: "ローカット・ミドル・ハイカットの違いを解説。" },
  { title: "ザックの選び方", url: "gear/pack.html", tags: "ザック バックパック 選び方 容量", desc: "日帰りから縦走まで用途別のおすすめザック。" },
  { title: "レインウェアの選び方", url: "gear/rain.html", tags: "レインウェア 雨具 ゴアテックス 防水", desc: "登山用レインウェアの選び方とおすすめ。" },
  { title: "トレッキングポールの選び方", url: "gear/pole.html", tags: "ポール ストック 選び方", desc: "膝への負担を軽減するポールの使い方と選び方。" },
  { title: "ウェア・レイヤリング", url: "gear/wear.html", tags: "ウェア レイヤリング 速乾 防寒", desc: "登山の重ね着（レイヤリング）の基本。" },
  { title: "安全装備ガイド", url: "gear/safety.html", tags: "安全 ヘッドライト 救急 GPS 装備", desc: "緊急時に命を守る安全装備の選び方。" },
  { title: "富士山装備チェックリスト", url: "gear/fuji-checklist.html", tags: "富士山 装備 チェックリスト 持ち物", desc: "富士登山に必要な持ち物を完全リスト化。" },
  { title: "初級コース一覧", url: "difficulty/beginner.html", tags: "初級 初心者 簡単 日帰り", desc: "登山経験不要の初心者向けコース。" },
  { title: "中級コース一覧", url: "difficulty/intermediate.html", tags: "中級 体力 装備", desc: "基本装備と体力がある方向けのコース。" },
  { title: "上級コース一覧", url: "difficulty/advanced.html", tags: "上級 本格 経験者", desc: "十分な経験と装備が必要な本格登山コース。" },
  { title: "春のハイキング", url: "season/spring.html", tags: "春 桜 新緑 3月 4月 5月", desc: "桜・新緑を楽しむ春のおすすめコース。" },
  { title: "夏のハイキング", url: "season/summer.html", tags: "夏 富士山 アルプス 高山 6月 7月 8月", desc: "夏山・高山植物・富士登山の季節。" },
  { title: "秋のハイキング", url: "season/autumn.html", tags: "秋 紅葉 9月 10月 11月", desc: "紅葉が最高潮の秋のおすすめコース。" },
  { title: "冬のハイキング", url: "season/winter.html", tags: "冬 雪 スノーシュー 樹氷 12月 1月 2月", desc: "雪山・スノーシューを楽しむ冬のコース。" },
];
